-- ============================================================
-- InterviewVerseAI - Database Initialization Schema
-- ============================================================

-- Drop tables if they exist (for clean re-runs)
DROP TABLE IF EXISTS CAREER_READINESS CASCADE;
DROP TABLE IF EXISTS SKILL_GAPS CASCADE;
DROP TABLE IF EXISTS SKILL_ASSESSMENTS CASCADE;
DROP TABLE IF EXISTS INTERVIEW_ANSWERS CASCADE;
DROP TABLE IF EXISTS INTERVIEW_QUESTIONS CASCADE;
DROP TABLE IF EXISTS INTERVIEW_SESSIONS CASCADE;
DROP TABLE IF EXISTS CANDIDATE_PROFILES CASCADE;
DROP TABLE IF EXISTS USERS CASCADE;

-- 1. USERS TABLE
CREATE TABLE USERS (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(50) DEFAULT 'CANDIDATE' NOT NULL, -- 'CANDIDATE', 'ADMIN'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 2. CANDIDATE_PROFILES TABLE
CREATE TABLE CANDIDATE_PROFILES (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT UNIQUE NOT NULL REFERENCES USERS(id) ON DELETE CASCADE,
    education VARCHAR(255),
    experience VARCHAR(255),
    target_role VARCHAR(255) DEFAULT 'Software Developer',
    skills TEXT, -- Comma-separated or JSON list of skills
    resume_text TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 3. INTERVIEW_SESSIONS TABLE
CREATE TABLE INTERVIEW_SESSIONS (
    id BIGSERIAL PRIMARY KEY,
    candidate_id BIGINT NOT NULL REFERENCES USERS(id) ON DELETE CASCADE,
    interview_type VARCHAR(100) DEFAULT 'Mixed' NOT NULL, -- 'Technical', 'Problem Solving', 'Communication', 'Behavioral', 'Mixed'
    job_role VARCHAR(255) DEFAULT 'Software Developer' NOT NULL,
    status VARCHAR(50) DEFAULT 'IN_PROGRESS' NOT NULL, -- 'IN_PROGRESS', 'COMPLETED', 'CANCELLED'
    current_difficulty VARCHAR(50) DEFAULT 'EASY' NOT NULL, -- 'EASY', 'MEDIUM', 'HARD'
    started_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE,
    overall_score NUMERIC(5,2) DEFAULT 0.00
);

-- 4. INTERVIEW_QUESTIONS TABLE
CREATE TABLE INTERVIEW_QUESTIONS (
    id BIGSERIAL PRIMARY KEY,
    session_id BIGINT NOT NULL REFERENCES INTERVIEW_SESSIONS(id) ON DELETE CASCADE,
    question TEXT NOT NULL,
    category VARCHAR(100) NOT NULL, -- 'Technical', 'Problem Solving', 'Communication', 'Behavioral'
    topic VARCHAR(100) NOT NULL,
    difficulty VARCHAR(50) NOT NULL, -- 'EASY', 'MEDIUM', 'HARD'
    sequence_number INT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 5. INTERVIEW_ANSWERS TABLE
CREATE TABLE INTERVIEW_ANSWERS (
    id BIGSERIAL PRIMARY KEY,
    question_id BIGINT UNIQUE NOT NULL REFERENCES INTERVIEW_QUESTIONS(id) ON DELETE CASCADE,
    answer_text TEXT NOT NULL,
    audio_path VARCHAR(500),
    transcription TEXT,
    score NUMERIC(5,2) DEFAULT 0.00,
    correctness NUMERIC(5,2) DEFAULT 0.00,
    relevance NUMERIC(5,2) DEFAULT 0.00,
    completeness NUMERIC(5,2) DEFAULT 0.00,
    feedback TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 6. SKILL_ASSESSMENTS TABLE
CREATE TABLE SKILL_ASSESSMENTS (
    id BIGSERIAL PRIMARY KEY,
    session_id BIGINT UNIQUE NOT NULL REFERENCES INTERVIEW_SESSIONS(id) ON DELETE CASCADE,
    technical_score NUMERIC(5,2) DEFAULT 0.00,
    problem_solving_score NUMERIC(5,2) DEFAULT 0.00,
    communication_score NUMERIC(5,2) DEFAULT 0.00,
    behavioral_score NUMERIC(5,2) DEFAULT 0.00,
    overall_score NUMERIC(5,2) DEFAULT 0.00,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 7. SKILL_GAPS TABLE
CREATE TABLE SKILL_GAPS (
    id BIGSERIAL PRIMARY KEY,
    session_id BIGINT NOT NULL REFERENCES INTERVIEW_SESSIONS(id) ON DELETE CASCADE,
    skill_name VARCHAR(255) NOT NULL,
    current_level VARCHAR(50) NOT NULL,
    target_level VARCHAR(50) NOT NULL,
    recommendation TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 8. CAREER_READINESS TABLE
CREATE TABLE CAREER_READINESS (
    id BIGSERIAL PRIMARY KEY,
    session_id BIGINT UNIQUE NOT NULL REFERENCES INTERVIEW_SESSIONS(id) ON DELETE CASCADE,
    readiness_score NUMERIC(5,2) DEFAULT 0.00,
    readiness_level VARCHAR(100) DEFAULT 'BEGINNER READY' NOT NULL, -- 'NOT READY', 'BEGINNER READY', 'INTERVIEW READY', 'JOB READY'
    strengths TEXT, -- JSON Array of strengths
    weaknesses TEXT, -- JSON Array of weaknesses
    recommendations TEXT, -- JSON Array of recommendations
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Indexes for performance
CREATE INDEX idx_candidate_sessions ON INTERVIEW_SESSIONS(candidate_id);
CREATE INDEX idx_session_questions ON INTERVIEW_QUESTIONS(session_id);
CREATE INDEX idx_session_skill_assessments ON SKILL_ASSESSMENTS(session_id);
CREATE INDEX idx_session_career_readiness ON CAREER_READINESS(session_id);
